{% set name = "polars_ds" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/polars_ds-{{ version }}.tar.gz
  sha256: fae63d884fa7179454e0b7f533c85c329712a8c34c4430a6430a5598604b523e

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - maturin >=1.3.2
    - pip
  run:
    - python >=3.8
    - polars >=0.20.6,!=0.20.12
    - typing-extensions  # [py<=311]

test:
  imports:
    - polars_ds
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/polars-ds/
  summary: A package adds data science utilities to Polars dataframe
  dev_url: https://github.com/abstractqqq/staged-recipes
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - abstractqqq
